services:
  app:
    image: ${DOCKER_USERNAME}/${APP_NAME}:latest
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres-sql-spring-app
      - DB_USERNAME=${PG_DB_USERNAME}
      - DB_PASSWORD=${PG_DB_PASSWORD}
      - DB_NAME=${PG_DB_DB_NAME}
      - DB_PORT=5432
    depends_on:
      - db

  db:
    container_name: postgres-sql-spring-app
    image: postgres:17.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_DB_NAME}
      PGDATA: /data/postgres

    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres:

networks:
  default:
    name: spring-app-network
